# Generated by Django 3.2.7 on 2023-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.TextField(),
        ),
    ]
